### ISSUE TITLE
make nav widget in "top full" horizontal

### ISSUE THREAD

**Issue by redknite** [understrap/understrap#1042]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [x ] a Question
  - [x ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.2.x

### Other Comments
I added a nav menu widget to the top full sidebar.  Is there a way to make that menu horizontal?  I like to have it appear similar to the main nav if possible, but if it it's just vertical I believe I can take it from there.

I added a `display: inline-block` to the `<li>` items, but that still has everything off to the left instead of right and doesn't seem to address responsiveness.

**Comment by IanDelMar** [comment]
Assuming it is a top-level menu, you could try something similar to

SCSS version
```scss
ul#mynavid {
  @extend .nav;
  a {
    @extend .nav-link;
  }
}
```
CSS version
```scss
ul#mynavid {
  display: flex;
  flex-wrap: wrap;
  padding-left: 0;
  margin-bottom: 0;
  list-style: none;
}
ul#mynavid  a {
  display: block;
  padding: y-value x-value;
}
```
