### ISSUE TITLE
Adding alignwide and alignfull support

### ISSUE THREAD

**Issue by bacoords** [understrap/understrap#1294]
In the past, I've been able to add basic theme support for Gutenberg's wide and full alignment with this method. I plan to add it to a PR but want to start by documenting it as an issue for discussion. This basically works but I'm not sure how to deal with pages using sidebars. I don't think we can disable it in the editor if a sidebar is present, so we'll need to think about using container classes to make this at least functional, even if it's full width just within the content area... open to thoughts here.

In `inc/setup.php`:
```php
add_theme_support( 'align-wide' );
```

In our scss, perhaps in a new gutenberg-specific file:
```scss
 .alignleft,
 .alignright,
 .aligncenter {
	 display: block;
	 margin: 0.6rem auto;
 }
 
 @include media-breakpoint-up(md) {
	 .alignleft {
		 float: left;
		 margin-right: 1.25rem;
	 }
	 .alignright {
		 float: right;
		 margin-left: 1.25rem;
	 }
 }
 
 .alignwide,
 .alignfull, 
 .wp-block-cover.alignwide,
 .wp-block-cover.alignfull {
	 margin: 0px calc(50% - 50vw);
	 max-width: 100vw;
	 width: 100vw;
 
	 .wp-block-cover__inner-container {
		 @extend .container;
	 }
 }
 
 
 @media (max-width: 920px) {
	 .alignwide,
	 .wp-block-cover.alignwide {
		 margin: 32px calc( ( 767px - 920px ) / 2 );
		 max-width: 920px;
		 width: 920px;
	 }
 }
```
