### ISSUE TITLE
Registering bootstrap theme colors into the block editor

### ISSUE THREAD

**Issue by bacoords** [understrap/understrap#1295]
When users work in the block editor, the color choices should match the same color palette as bootstrap core. Similarly, when we update color variables in SCSS for child themes, we should be able to easily swap the colors there, too. There's two parts to setting up block editor colors: PHP support and actually adding the classes to the theme.

Adding the support code to the php. This has to be done manually. I'd eventually love to use the theme.json that WP is developing, feed that into gulp, and autogenerate our color variables, but I don't see that happening right away. So for now, this has to be manually updated IF you change your colors.
```php
add_theme_support( 'editor-color-palette', array(
    array(
        'name' => esc_attr__( 'purple', 'understrap' ),
        'slug' => 'purple',
        'color' => '#a156b4',
    ),
   [...]
));
```

Adding the appropriate classes to the scss. Luckily this can be autogenerated from the variables:
```scss
@each $name, $color in $colors {

	.has-#{$name}-color,
	.has-#{$name}-color:visited {
		color: $color;
	}
	.has-#{$name}-background-color {
		background-color: $color;
		border-color: $color;
	}
}
@each $name, $color in $theme-colors {

	.has-#{$name}-color,
	.has-#{$name}-color:visited {
		color: $color;
	}
	.has-#{$name}-background-color {
		background-color: $color;
		border-color: $color;
	}
}
```
