### ISSUE TITLE
Feature Request: Better support of Bootstrap inside the block editor

### ISSUE THREAD

**Issue by bacoords** [understrap/understrap#2083]
We've been slowly adding some bootstrap features into the block editor (which has gotten easier over time as the block editor's classes get more scoped and stable). This issue will be a checklist of things I've been doing in my custom child themes to make the `src/sass/custom-editor-style.scss` file more useful. The goal would be to bring these into understrap.

- [ ] Importing the bootstrap grid / containers
- [ ] Mapping the block width to the bootstrap containers

## Problem Statement

The block editor still doesn't quite match the front-end

## Who will benefit?

Anyone using the block editor but especially those using Bootstrap grid classes in their columns.

## Benefits and risks

There'll probably be a lot of compatibility checking. For example, anyone using the container-fluid globally will still not see the right layouts (but it will be closer).

## Proposed solution

`src/sass/custom-editor-style.scss`:

**Importing the bootstrap grid / containers**
This allows for more integration in custom/acf blocks.
```scss
@import "assets/bootstrap5/containers";
@import "assets/bootstrap5/grid";
```

**Mapping the block width to the bootstrap containers:**
Because blocks don't get the max-width on the front-end that Gutenberg provides on the backend (and because there's no way to tell Gutenberg that you have multiple max-widths) this is a decent middle ground that better approximates the front end
```scss
@each $breakpoint, $container-max-width in $container-max-widths {
    @include media-breakpoint-up($breakpoint, $grid-breakpoints) {
		html :where(.wp-block) {
			max-width: $container-max-width;
		}
	}
}
```

## Priority/Severity

- [ ] High (This will bring a huge increase in performance/productivity/usability/legislative cover)
- [x] Medium (This will bring a good increase in performance/productivity/usability)
- [ ] Low (anything else e.g., trivial, minor improvements)
