### ISSUE TITLE
Problem using WooCommerce with Understrap...

### ISSUE THREAD

**Issue by tambovskya** [understrap/understrap#950]
If you are experiencing problems with things not working on the checkout page with WooCommerce. The problem might be with because of this line in the understrap/inc/woocommerce.php file: **understrap_wc_form_field_args**. 

I am unable to checkout on my website with this line in the woocommerce.php file, specifically I'm using the Intuit Payments Gateway plugin for WooCommerce, but I experienced problems with BitPay plugin, and actually tried getting in contact with them because I though it was an issue with their plugin.

Developer, please fix this. It does not work. Thank you.

**Comment by monkishtypist** [comment]
I encountered a problem as well using Understrap with Authorize.net CIM plugin for WooCommerce. Specifically I received an error with `Accept.js`:
```
Accept.js Error: payment nonce is missing
``` 

Rather than modifying Understrap theme, I fixed this by doing the following:

1. Add the following function to Child theme `functions.php`. This essentially removes the Bootstrap classes that are added to the Checkout form fields.
```PHP
if ( ! function_exists( 'understrap_wc_form_field_args' ) ) {
	// This function replaces the Understrap function of the same name
	function understrap_wc_form_field_args( $args, $key, $value = null ) {
		return $args;
	}
}
```

2. Extend the CSS classes used by WooCommerce to use Bootstrap CSS classes with the following in `_child_theme.scss`:
```SCSS
.woocommerce-checkout {
    .form-row {
        @extend .form-group;
        .woocommerce-input-wrapper {
            width: 100%;
            input,
            select,
            textarea {
                @extend .form-control;
            }
        }
    }
}
```
Recompile with `gulp styles` and this should replace the need for Bootstrap classes to be written into the code, and does not affect core functionality.

I reached out to Authorize.net CIM plugin author for support to see if they could identify the exact cause of the issue with the Understrap code and am waiting to hear back.
