### ISSUE TITLE
Custom font not working on mobile

### ISSUE THREAD

**Issue by Bare-Guillaume** [understrap/understrap#994]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] I need help getting custom font to display on mobile

## Please tell us about your environment:

  - **WordPress Version:** 5.2.2 MacOS [10.14.3]| iOS [12.3.1]
  - **Browser:**  | iOS Safari ]
 
I have added custom fonts like so 

```
@font-face {
  font-family: PALSCRI;  
  src:url(http://bobeauspa.local/wp-content/themes/understrap-child/fonts/palace-script-mt.eot) format('eot'),
      url(http://bobeauspa.local/wp-content/themes/understrap-child/fonts/palace-script-mt.woff) format('woff'),
      url(http://bobeauspa.local/wp-content/themes/understrap-child/fonts/palace-script-mt.woff2) format('woff2'),
      url(http://bobeauspa.local/wp-content/themes/understrap-child/fonts/palace-script-mt.ttf) format('truetype'),
      url(http://bobeauspa.local/wp-content/themes/understrap-child/fonts/palace-script-mt.svg) format('svg');
      font-weight: normal;
	    font-style: normal; 
}

It is displaying perfectly on desktop with chrome, safari, and firefox however it doesn't on my iPhone.

I followed different threads on how to add custom fonts and I believe the method I used is the way to go but it's not working.

Where am I mistaking?

**Comment by Thomas-A-Reinert** [comment]
Are you calling the domain bobeauspa.local from your iPhone? Seems like it can´t resolve it. I´d use relative path anyway. Makes migration a whole lot easier.

I assume you noted this in your `./sass/theme/_theme.scss` which gets compiled to `./css/theme.min.css`, correct? Then I´d do it like this which always works for me:

```CSS
@font-face {
  font-family: 'Raleway';
  font-style: normal;
  font-weight: 400;
  src: url('../fonts/raleway-v13-latin-regular.eot'); /* IE9 Compat Modes */
  src: local('Raleway'), local('Raleway-Regular'),
       url('../fonts/raleway-v13-latin-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('../fonts/raleway-v13-latin-regular.woff2') format('woff2'), /* Super Modern Browsers */
       url('../fonts/raleway-v13-latin-regular.woff') format('woff'), /* Modern Browsers */
       url('../fonts/raleway-v13-latin-regular.ttf') format('truetype'), /* Safari, Android, iOS */
       url('../fonts/raleway-v13-latin-regular.svg#Raleway') format('svg'); /* Legacy iOS */
}
```
